backend:
  replicas: 2

  image:
    repository: devops-crud-app-backend
    tag: latest
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 5000

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  probes:
    startup:
      path: /healthz
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 12

    liveness:
      path: /healthz
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

    readiness:
      path: /healthz
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

# Backend Horizontal Pod Autoscaler
backendHPA:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

frontend:
  replicas: 2

  image:
    repository: devops-crud-app-frontend
    tag: latest
    pullPolicy: Never

  service:
    type: ClusterIP
    port: 3000

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

    limits:
      cpu: "500m"
      memory: "512Mi"

  probes:
    startup:
      path: /
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 12

    liveness:
      path: /
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3

    readiness:
      path: /
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3

frontendHPA:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
