apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}

type: Opaque

stringData:
  JWT_SECRET: {{ .Values.secrets.backend.JWT_SECRET | quote }}
