apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-crud-app.fullname" . }}-frontend
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}
    app: frontend

spec:
  replicas: {{ .Values.frontend.replicas }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

          startupProbe:
            httpGet:
              path: {{ .Values.frontend.probes.startup.path }}
              port: 3000
            initialDelaySeconds: {{ .Values.frontend.probes.startup.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.startup.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.startup.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.liveness.path }}
              port: 3000
            periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}

          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probes.readiness.path }}
              port: 3000
            periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}

          env:
            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: VITE_API_URL