{{- if .Values.frontendHPA.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "devops-crud-app.fullname" . }}-frontend-hpa
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}
    app: frontend

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "devops-crud-app.fullname" . }}-frontend

  minReplicas: {{ .Values.frontendHPA.minReplicas }}
  maxReplicas: {{ .Values.frontendHPA.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontendHPA.targetCPUUtilizationPercentage }}
{{- end }}