apiVersion: v1
kind: Service

metadata:
  name: {{ include "devops-crud-app.fullname" . }}-postgres

  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}
    app: postgres

spec:
  clusterIP: None

  selector:
    app: postgres

  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP