apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}

type: Opaque

stringData:
  POSTGRES_DB: {{ .Values.secrets.postgres.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.POSTGRES_PASSWORD | quote }}
