{{- if .Values.backendHPA.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "devops-crud-app.fullname" . }}-backend-hpa
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}
    app: backend

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "devops-crud-app.fullname" . }}-backend

  minReplicas: {{ .Values.backendHPA.minReplicas }}
  maxReplicas: {{ .Values.backendHPA.maxReplicas }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backendHPA.targetCPUUtilizationPercentage }}
{{- end }}