apiVersion: v1
kind: ConfigMap

metadata:
  name: frontend-config
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}

data:
  VITE_API_URL: {{ .Values.config.frontend.VITE_API_URL | quote }}
  BACKEND_HOST: {{ include "devops-crud-app.fullname" . }}-backend
