apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: {{ include "devops-crud-app.fullname" . }}-postgres
  labels:
    {{- include "devops-crud-app.labels" . | nindent 4 }}
    app: postgres

spec:
  serviceName: {{ include "devops-crud-app.fullname" . }}-postgres
  replicas: {{ .Values.postgres.replicas }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        {{- include "devops-crud-app.labels" . | nindent 8 }}
        app: postgres

    spec:
      containers:
        - name: postgres

          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: {{ .Values.postgres.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.liveness.failureThreshold }}

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: {{ .Values.postgres.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.postgres.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.postgres.probes.readiness.failureThreshold }}

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

  # volumeClaimTemplates auto-creates a PVC for EACH pod
  # This is what makes StatefulSet special for databases
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - {{ .Values.postgres.storage.accessMode }}
        storageClassName: {{ .Values.postgres.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.postgres.storage.size }}
